// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/ensembleproposer"
	"github.com/Wei-Shaw/sub2api/ent/group"
)

// EnsembleProposer is the model entity for the EnsembleProposer schema.
type EnsembleProposer struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// DeletedAt holds the value of the "deleted_at" field.
	DeletedAt *time.Time `json:"deleted_at,omitempty"`
	// GroupID holds the value of the "group_id" field.
	GroupID int64 `json:"group_id,omitempty"`
	// proposer or aggregator.
	Role string `json:"role,omitempty"`
	// Model identifier served by the group's own accounts.
	Model string `json:"model,omitempty"`
	// Concrete upstream platform used to serve this model.
	Platform string `json:"platform,omitempty"`
	// Lower values are called/displayed first among proposers.
	Priority int `json:"priority,omitempty"`
	// Enabled holds the value of the "enabled" field.
	Enabled bool `json:"enabled,omitempty"`
	// whether the member model accepts image inputs.
	Vision bool `json:"vision,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the EnsembleProposerQuery when eager-loading is set.
	Edges        EnsembleProposerEdges `json:"edges"`
	selectValues sql.SelectValues
}

// EnsembleProposerEdges holds the relations/edges for other nodes in the graph.
type EnsembleProposerEdges struct {
	// Group holds the value of the group edge.
	Group *Group `json:"group,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// GroupOrErr returns the Group value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e EnsembleProposerEdges) GroupOrErr() (*Group, error) {
	if e.Group != nil {
		return e.Group, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: group.Label}
	}
	return nil, &NotLoadedError{edge: "group"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*EnsembleProposer) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case ensembleproposer.FieldEnabled, ensembleproposer.FieldVision:
			values[i] = new(sql.NullBool)
		case ensembleproposer.FieldID, ensembleproposer.FieldGroupID, ensembleproposer.FieldPriority:
			values[i] = new(sql.NullInt64)
		case ensembleproposer.FieldRole, ensembleproposer.FieldModel, ensembleproposer.FieldPlatform:
			values[i] = new(sql.NullString)
		case ensembleproposer.FieldCreatedAt, ensembleproposer.FieldUpdatedAt, ensembleproposer.FieldDeletedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the EnsembleProposer fields.
func (_m *EnsembleProposer) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case ensembleproposer.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case ensembleproposer.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case ensembleproposer.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case ensembleproposer.FieldDeletedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field deleted_at", values[i])
			} else if value.Valid {
				_m.DeletedAt = new(time.Time)
				*_m.DeletedAt = value.Time
			}
		case ensembleproposer.FieldGroupID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field group_id", values[i])
			} else if value.Valid {
				_m.GroupID = value.Int64
			}
		case ensembleproposer.FieldRole:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field role", values[i])
			} else if value.Valid {
				_m.Role = value.String
			}
		case ensembleproposer.FieldModel:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field model", values[i])
			} else if value.Valid {
				_m.Model = value.String
			}
		case ensembleproposer.FieldPlatform:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field platform", values[i])
			} else if value.Valid {
				_m.Platform = value.String
			}
		case ensembleproposer.FieldPriority:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field priority", values[i])
			} else if value.Valid {
				_m.Priority = int(value.Int64)
			}
		case ensembleproposer.FieldEnabled:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field enabled", values[i])
			} else if value.Valid {
				_m.Enabled = value.Bool
			}
		case ensembleproposer.FieldVision:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field vision", values[i])
			} else if value.Valid {
				_m.Vision = value.Bool
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the EnsembleProposer.
// This includes values selected through modifiers, order, etc.
func (_m *EnsembleProposer) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryGroup queries the "group" edge of the EnsembleProposer entity.
func (_m *EnsembleProposer) QueryGroup() *GroupQuery {
	return NewEnsembleProposerClient(_m.config).QueryGroup(_m)
}

// Update returns a builder for updating this EnsembleProposer.
// Note that you need to call EnsembleProposer.Unwrap() before calling this method if this EnsembleProposer
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *EnsembleProposer) Update() *EnsembleProposerUpdateOne {
	return NewEnsembleProposerClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the EnsembleProposer entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *EnsembleProposer) Unwrap() *EnsembleProposer {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: EnsembleProposer is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *EnsembleProposer) String() string {
	var builder strings.Builder
	builder.WriteString("EnsembleProposer(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	if v := _m.DeletedAt; v != nil {
		builder.WriteString("deleted_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("group_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.GroupID))
	builder.WriteString(", ")
	builder.WriteString("role=")
	builder.WriteString(_m.Role)
	builder.WriteString(", ")
	builder.WriteString("model=")
	builder.WriteString(_m.Model)
	builder.WriteString(", ")
	builder.WriteString("platform=")
	builder.WriteString(_m.Platform)
	builder.WriteString(", ")
	builder.WriteString("priority=")
	builder.WriteString(fmt.Sprintf("%v", _m.Priority))
	builder.WriteString(", ")
	builder.WriteString("enabled=")
	builder.WriteString(fmt.Sprintf("%v", _m.Enabled))
	builder.WriteString(", ")
	builder.WriteString("vision=")
	builder.WriteString(fmt.Sprintf("%v", _m.Vision))
	builder.WriteByte(')')
	return builder.String()
}

// EnsembleProposers is a parsable slice of EnsembleProposer.
type EnsembleProposers []*EnsembleProposer
