// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/ensembleproposer"
	"github.com/Wei-Shaw/sub2api/ent/group"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// EnsembleProposerUpdate is the builder for updating EnsembleProposer entities.
type EnsembleProposerUpdate struct {
	config
	hooks    []Hook
	mutation *EnsembleProposerMutation
}

// Where appends a list predicates to the EnsembleProposerUpdate builder.
func (_u *EnsembleProposerUpdate) Where(ps ...predicate.EnsembleProposer) *EnsembleProposerUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *EnsembleProposerUpdate) SetUpdatedAt(v time.Time) *EnsembleProposerUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *EnsembleProposerUpdate) SetDeletedAt(v time.Time) *EnsembleProposerUpdate {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *EnsembleProposerUpdate) SetNillableDeletedAt(v *time.Time) *EnsembleProposerUpdate {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *EnsembleProposerUpdate) ClearDeletedAt() *EnsembleProposerUpdate {
	_u.mutation.ClearDeletedAt()
	return _u
}

// SetGroupID sets the "group_id" field.
func (_u *EnsembleProposerUpdate) SetGroupID(v int64) *EnsembleProposerUpdate {
	_u.mutation.SetGroupID(v)
	return _u
}

// SetNillableGroupID sets the "group_id" field if the given value is not nil.
func (_u *EnsembleProposerUpdate) SetNillableGroupID(v *int64) *EnsembleProposerUpdate {
	if v != nil {
		_u.SetGroupID(*v)
	}
	return _u
}

// SetRole sets the "role" field.
func (_u *EnsembleProposerUpdate) SetRole(v string) *EnsembleProposerUpdate {
	_u.mutation.SetRole(v)
	return _u
}

// SetNillableRole sets the "role" field if the given value is not nil.
func (_u *EnsembleProposerUpdate) SetNillableRole(v *string) *EnsembleProposerUpdate {
	if v != nil {
		_u.SetRole(*v)
	}
	return _u
}

// SetModel sets the "model" field.
func (_u *EnsembleProposerUpdate) SetModel(v string) *EnsembleProposerUpdate {
	_u.mutation.SetModel(v)
	return _u
}

// SetNillableModel sets the "model" field if the given value is not nil.
func (_u *EnsembleProposerUpdate) SetNillableModel(v *string) *EnsembleProposerUpdate {
	if v != nil {
		_u.SetModel(*v)
	}
	return _u
}

// SetPlatform sets the "platform" field.
func (_u *EnsembleProposerUpdate) SetPlatform(v string) *EnsembleProposerUpdate {
	_u.mutation.SetPlatform(v)
	return _u
}

// SetNillablePlatform sets the "platform" field if the given value is not nil.
func (_u *EnsembleProposerUpdate) SetNillablePlatform(v *string) *EnsembleProposerUpdate {
	if v != nil {
		_u.SetPlatform(*v)
	}
	return _u
}

// SetPriority sets the "priority" field.
func (_u *EnsembleProposerUpdate) SetPriority(v int) *EnsembleProposerUpdate {
	_u.mutation.ResetPriority()
	_u.mutation.SetPriority(v)
	return _u
}

// SetNillablePriority sets the "priority" field if the given value is not nil.
func (_u *EnsembleProposerUpdate) SetNillablePriority(v *int) *EnsembleProposerUpdate {
	if v != nil {
		_u.SetPriority(*v)
	}
	return _u
}

// AddPriority adds value to the "priority" field.
func (_u *EnsembleProposerUpdate) AddPriority(v int) *EnsembleProposerUpdate {
	_u.mutation.AddPriority(v)
	return _u
}

// SetEnabled sets the "enabled" field.
func (_u *EnsembleProposerUpdate) SetEnabled(v bool) *EnsembleProposerUpdate {
	_u.mutation.SetEnabled(v)
	return _u
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_u *EnsembleProposerUpdate) SetNillableEnabled(v *bool) *EnsembleProposerUpdate {
	if v != nil {
		_u.SetEnabled(*v)
	}
	return _u
}

// SetVision sets the "vision" field.
func (_u *EnsembleProposerUpdate) SetVision(v bool) *EnsembleProposerUpdate {
	_u.mutation.SetVision(v)
	return _u
}

// SetNillableVision sets the "vision" field if the given value is not nil.
func (_u *EnsembleProposerUpdate) SetNillableVision(v *bool) *EnsembleProposerUpdate {
	if v != nil {
		_u.SetVision(*v)
	}
	return _u
}

// SetGroup sets the "group" edge to the Group entity.
func (_u *EnsembleProposerUpdate) SetGroup(v *Group) *EnsembleProposerUpdate {
	return _u.SetGroupID(v.ID)
}

// Mutation returns the EnsembleProposerMutation object of the builder.
func (_u *EnsembleProposerUpdate) Mutation() *EnsembleProposerMutation {
	return _u.mutation
}

// ClearGroup clears the "group" edge to the Group entity.
func (_u *EnsembleProposerUpdate) ClearGroup() *EnsembleProposerUpdate {
	_u.mutation.ClearGroup()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *EnsembleProposerUpdate) Save(ctx context.Context) (int, error) {
	if err := _u.defaults(); err != nil {
		return 0, err
	}
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *EnsembleProposerUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *EnsembleProposerUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *EnsembleProposerUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *EnsembleProposerUpdate) defaults() error {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		if ensembleproposer.UpdateDefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized ensembleproposer.UpdateDefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := ensembleproposer.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_u *EnsembleProposerUpdate) check() error {
	if v, ok := _u.mutation.Role(); ok {
		if err := ensembleproposer.RoleValidator(v); err != nil {
			return &ValidationError{Name: "role", err: fmt.Errorf(`ent: validator failed for field "EnsembleProposer.role": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Model(); ok {
		if err := ensembleproposer.ModelValidator(v); err != nil {
			return &ValidationError{Name: "model", err: fmt.Errorf(`ent: validator failed for field "EnsembleProposer.model": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Platform(); ok {
		if err := ensembleproposer.PlatformValidator(v); err != nil {
			return &ValidationError{Name: "platform", err: fmt.Errorf(`ent: validator failed for field "EnsembleProposer.platform": %w`, err)}
		}
	}
	if _u.mutation.GroupCleared() && len(_u.mutation.GroupIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "EnsembleProposer.group"`)
	}
	return nil
}

func (_u *EnsembleProposerUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(ensembleproposer.Table, ensembleproposer.Columns, sqlgraph.NewFieldSpec(ensembleproposer.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(ensembleproposer.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(ensembleproposer.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(ensembleproposer.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.Role(); ok {
		_spec.SetField(ensembleproposer.FieldRole, field.TypeString, value)
	}
	if value, ok := _u.mutation.Model(); ok {
		_spec.SetField(ensembleproposer.FieldModel, field.TypeString, value)
	}
	if value, ok := _u.mutation.Platform(); ok {
		_spec.SetField(ensembleproposer.FieldPlatform, field.TypeString, value)
	}
	if value, ok := _u.mutation.Priority(); ok {
		_spec.SetField(ensembleproposer.FieldPriority, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedPriority(); ok {
		_spec.AddField(ensembleproposer.FieldPriority, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Enabled(); ok {
		_spec.SetField(ensembleproposer.FieldEnabled, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Vision(); ok {
		_spec.SetField(ensembleproposer.FieldVision, field.TypeBool, value)
	}
	if _u.mutation.GroupCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   ensembleproposer.GroupTable,
			Columns: []string{ensembleproposer.GroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.GroupIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   ensembleproposer.GroupTable,
			Columns: []string{ensembleproposer.GroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{ensembleproposer.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// EnsembleProposerUpdateOne is the builder for updating a single EnsembleProposer entity.
type EnsembleProposerUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *EnsembleProposerMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *EnsembleProposerUpdateOne) SetUpdatedAt(v time.Time) *EnsembleProposerUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *EnsembleProposerUpdateOne) SetDeletedAt(v time.Time) *EnsembleProposerUpdateOne {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *EnsembleProposerUpdateOne) SetNillableDeletedAt(v *time.Time) *EnsembleProposerUpdateOne {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *EnsembleProposerUpdateOne) ClearDeletedAt() *EnsembleProposerUpdateOne {
	_u.mutation.ClearDeletedAt()
	return _u
}

// SetGroupID sets the "group_id" field.
func (_u *EnsembleProposerUpdateOne) SetGroupID(v int64) *EnsembleProposerUpdateOne {
	_u.mutation.SetGroupID(v)
	return _u
}

// SetNillableGroupID sets the "group_id" field if the given value is not nil.
func (_u *EnsembleProposerUpdateOne) SetNillableGroupID(v *int64) *EnsembleProposerUpdateOne {
	if v != nil {
		_u.SetGroupID(*v)
	}
	return _u
}

// SetRole sets the "role" field.
func (_u *EnsembleProposerUpdateOne) SetRole(v string) *EnsembleProposerUpdateOne {
	_u.mutation.SetRole(v)
	return _u
}

// SetNillableRole sets the "role" field if the given value is not nil.
func (_u *EnsembleProposerUpdateOne) SetNillableRole(v *string) *EnsembleProposerUpdateOne {
	if v != nil {
		_u.SetRole(*v)
	}
	return _u
}

// SetModel sets the "model" field.
func (_u *EnsembleProposerUpdateOne) SetModel(v string) *EnsembleProposerUpdateOne {
	_u.mutation.SetModel(v)
	return _u
}

// SetNillableModel sets the "model" field if the given value is not nil.
func (_u *EnsembleProposerUpdateOne) SetNillableModel(v *string) *EnsembleProposerUpdateOne {
	if v != nil {
		_u.SetModel(*v)
	}
	return _u
}

// SetPlatform sets the "platform" field.
func (_u *EnsembleProposerUpdateOne) SetPlatform(v string) *EnsembleProposerUpdateOne {
	_u.mutation.SetPlatform(v)
	return _u
}

// SetNillablePlatform sets the "platform" field if the given value is not nil.
func (_u *EnsembleProposerUpdateOne) SetNillablePlatform(v *string) *EnsembleProposerUpdateOne {
	if v != nil {
		_u.SetPlatform(*v)
	}
	return _u
}

// SetPriority sets the "priority" field.
func (_u *EnsembleProposerUpdateOne) SetPriority(v int) *EnsembleProposerUpdateOne {
	_u.mutation.ResetPriority()
	_u.mutation.SetPriority(v)
	return _u
}

// SetNillablePriority sets the "priority" field if the given value is not nil.
func (_u *EnsembleProposerUpdateOne) SetNillablePriority(v *int) *EnsembleProposerUpdateOne {
	if v != nil {
		_u.SetPriority(*v)
	}
	return _u
}

// AddPriority adds value to the "priority" field.
func (_u *EnsembleProposerUpdateOne) AddPriority(v int) *EnsembleProposerUpdateOne {
	_u.mutation.AddPriority(v)
	return _u
}

// SetEnabled sets the "enabled" field.
func (_u *EnsembleProposerUpdateOne) SetEnabled(v bool) *EnsembleProposerUpdateOne {
	_u.mutation.SetEnabled(v)
	return _u
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_u *EnsembleProposerUpdateOne) SetNillableEnabled(v *bool) *EnsembleProposerUpdateOne {
	if v != nil {
		_u.SetEnabled(*v)
	}
	return _u
}

// SetVision sets the "vision" field.
func (_u *EnsembleProposerUpdateOne) SetVision(v bool) *EnsembleProposerUpdateOne {
	_u.mutation.SetVision(v)
	return _u
}

// SetNillableVision sets the "vision" field if the given value is not nil.
func (_u *EnsembleProposerUpdateOne) SetNillableVision(v *bool) *EnsembleProposerUpdateOne {
	if v != nil {
		_u.SetVision(*v)
	}
	return _u
}

// SetGroup sets the "group" edge to the Group entity.
func (_u *EnsembleProposerUpdateOne) SetGroup(v *Group) *EnsembleProposerUpdateOne {
	return _u.SetGroupID(v.ID)
}

// Mutation returns the EnsembleProposerMutation object of the builder.
func (_u *EnsembleProposerUpdateOne) Mutation() *EnsembleProposerMutation {
	return _u.mutation
}

// ClearGroup clears the "group" edge to the Group entity.
func (_u *EnsembleProposerUpdateOne) ClearGroup() *EnsembleProposerUpdateOne {
	_u.mutation.ClearGroup()
	return _u
}

// Where appends a list predicates to the EnsembleProposerUpdate builder.
func (_u *EnsembleProposerUpdateOne) Where(ps ...predicate.EnsembleProposer) *EnsembleProposerUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *EnsembleProposerUpdateOne) Select(field string, fields ...string) *EnsembleProposerUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated EnsembleProposer entity.
func (_u *EnsembleProposerUpdateOne) Save(ctx context.Context) (*EnsembleProposer, error) {
	if err := _u.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *EnsembleProposerUpdateOne) SaveX(ctx context.Context) *EnsembleProposer {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *EnsembleProposerUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *EnsembleProposerUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *EnsembleProposerUpdateOne) defaults() error {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		if ensembleproposer.UpdateDefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized ensembleproposer.UpdateDefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := ensembleproposer.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_u *EnsembleProposerUpdateOne) check() error {
	if v, ok := _u.mutation.Role(); ok {
		if err := ensembleproposer.RoleValidator(v); err != nil {
			return &ValidationError{Name: "role", err: fmt.Errorf(`ent: validator failed for field "EnsembleProposer.role": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Model(); ok {
		if err := ensembleproposer.ModelValidator(v); err != nil {
			return &ValidationError{Name: "model", err: fmt.Errorf(`ent: validator failed for field "EnsembleProposer.model": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Platform(); ok {
		if err := ensembleproposer.PlatformValidator(v); err != nil {
			return &ValidationError{Name: "platform", err: fmt.Errorf(`ent: validator failed for field "EnsembleProposer.platform": %w`, err)}
		}
	}
	if _u.mutation.GroupCleared() && len(_u.mutation.GroupIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "EnsembleProposer.group"`)
	}
	return nil
}

func (_u *EnsembleProposerUpdateOne) sqlSave(ctx context.Context) (_node *EnsembleProposer, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(ensembleproposer.Table, ensembleproposer.Columns, sqlgraph.NewFieldSpec(ensembleproposer.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "EnsembleProposer.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, ensembleproposer.FieldID)
		for _, f := range fields {
			if !ensembleproposer.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != ensembleproposer.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(ensembleproposer.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(ensembleproposer.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(ensembleproposer.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.Role(); ok {
		_spec.SetField(ensembleproposer.FieldRole, field.TypeString, value)
	}
	if value, ok := _u.mutation.Model(); ok {
		_spec.SetField(ensembleproposer.FieldModel, field.TypeString, value)
	}
	if value, ok := _u.mutation.Platform(); ok {
		_spec.SetField(ensembleproposer.FieldPlatform, field.TypeString, value)
	}
	if value, ok := _u.mutation.Priority(); ok {
		_spec.SetField(ensembleproposer.FieldPriority, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedPriority(); ok {
		_spec.AddField(ensembleproposer.FieldPriority, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Enabled(); ok {
		_spec.SetField(ensembleproposer.FieldEnabled, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Vision(); ok {
		_spec.SetField(ensembleproposer.FieldVision, field.TypeBool, value)
	}
	if _u.mutation.GroupCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   ensembleproposer.GroupTable,
			Columns: []string{ensembleproposer.GroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.GroupIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   ensembleproposer.GroupTable,
			Columns: []string{ensembleproposer.GroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &EnsembleProposer{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{ensembleproposer.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
