// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/ensembleproposer"
	"github.com/Wei-Shaw/sub2api/ent/group"
)

// EnsembleProposerCreate is the builder for creating a EnsembleProposer entity.
type EnsembleProposerCreate struct {
	config
	mutation *EnsembleProposerMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (_c *EnsembleProposerCreate) SetCreatedAt(v time.Time) *EnsembleProposerCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *EnsembleProposerCreate) SetNillableCreatedAt(v *time.Time) *EnsembleProposerCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *EnsembleProposerCreate) SetUpdatedAt(v time.Time) *EnsembleProposerCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *EnsembleProposerCreate) SetNillableUpdatedAt(v *time.Time) *EnsembleProposerCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetDeletedAt sets the "deleted_at" field.
func (_c *EnsembleProposerCreate) SetDeletedAt(v time.Time) *EnsembleProposerCreate {
	_c.mutation.SetDeletedAt(v)
	return _c
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_c *EnsembleProposerCreate) SetNillableDeletedAt(v *time.Time) *EnsembleProposerCreate {
	if v != nil {
		_c.SetDeletedAt(*v)
	}
	return _c
}

// SetGroupID sets the "group_id" field.
func (_c *EnsembleProposerCreate) SetGroupID(v int64) *EnsembleProposerCreate {
	_c.mutation.SetGroupID(v)
	return _c
}

// SetRole sets the "role" field.
func (_c *EnsembleProposerCreate) SetRole(v string) *EnsembleProposerCreate {
	_c.mutation.SetRole(v)
	return _c
}

// SetNillableRole sets the "role" field if the given value is not nil.
func (_c *EnsembleProposerCreate) SetNillableRole(v *string) *EnsembleProposerCreate {
	if v != nil {
		_c.SetRole(*v)
	}
	return _c
}

// SetModel sets the "model" field.
func (_c *EnsembleProposerCreate) SetModel(v string) *EnsembleProposerCreate {
	_c.mutation.SetModel(v)
	return _c
}

// SetPlatform sets the "platform" field.
func (_c *EnsembleProposerCreate) SetPlatform(v string) *EnsembleProposerCreate {
	_c.mutation.SetPlatform(v)
	return _c
}

// SetNillablePlatform sets the "platform" field if the given value is not nil.
func (_c *EnsembleProposerCreate) SetNillablePlatform(v *string) *EnsembleProposerCreate {
	if v != nil {
		_c.SetPlatform(*v)
	}
	return _c
}

// SetPriority sets the "priority" field.
func (_c *EnsembleProposerCreate) SetPriority(v int) *EnsembleProposerCreate {
	_c.mutation.SetPriority(v)
	return _c
}

// SetNillablePriority sets the "priority" field if the given value is not nil.
func (_c *EnsembleProposerCreate) SetNillablePriority(v *int) *EnsembleProposerCreate {
	if v != nil {
		_c.SetPriority(*v)
	}
	return _c
}

// SetEnabled sets the "enabled" field.
func (_c *EnsembleProposerCreate) SetEnabled(v bool) *EnsembleProposerCreate {
	_c.mutation.SetEnabled(v)
	return _c
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_c *EnsembleProposerCreate) SetNillableEnabled(v *bool) *EnsembleProposerCreate {
	if v != nil {
		_c.SetEnabled(*v)
	}
	return _c
}

// SetGroup sets the "group" edge to the Group entity.
func (_c *EnsembleProposerCreate) SetGroup(v *Group) *EnsembleProposerCreate {
	return _c.SetGroupID(v.ID)
}

// Mutation returns the EnsembleProposerMutation object of the builder.
func (_c *EnsembleProposerCreate) Mutation() *EnsembleProposerMutation {
	return _c.mutation
}

// Save creates the EnsembleProposer in the database.
func (_c *EnsembleProposerCreate) Save(ctx context.Context) (*EnsembleProposer, error) {
	if err := _c.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *EnsembleProposerCreate) SaveX(ctx context.Context) *EnsembleProposer {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *EnsembleProposerCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *EnsembleProposerCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *EnsembleProposerCreate) defaults() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		if ensembleproposer.DefaultCreatedAt == nil {
			return fmt.Errorf("ent: uninitialized ensembleproposer.DefaultCreatedAt (forgotten import ent/runtime?)")
		}
		v := ensembleproposer.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		if ensembleproposer.DefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized ensembleproposer.DefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := ensembleproposer.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.Role(); !ok {
		v := ensembleproposer.DefaultRole
		_c.mutation.SetRole(v)
	}
	if _, ok := _c.mutation.Platform(); !ok {
		v := ensembleproposer.DefaultPlatform
		_c.mutation.SetPlatform(v)
	}
	if _, ok := _c.mutation.Priority(); !ok {
		v := ensembleproposer.DefaultPriority
		_c.mutation.SetPriority(v)
	}
	if _, ok := _c.mutation.Enabled(); !ok {
		v := ensembleproposer.DefaultEnabled
		_c.mutation.SetEnabled(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_c *EnsembleProposerCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "EnsembleProposer.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "EnsembleProposer.updated_at"`)}
	}
	if _, ok := _c.mutation.GroupID(); !ok {
		return &ValidationError{Name: "group_id", err: errors.New(`ent: missing required field "EnsembleProposer.group_id"`)}
	}
	if _, ok := _c.mutation.Role(); !ok {
		return &ValidationError{Name: "role", err: errors.New(`ent: missing required field "EnsembleProposer.role"`)}
	}
	if v, ok := _c.mutation.Role(); ok {
		if err := ensembleproposer.RoleValidator(v); err != nil {
			return &ValidationError{Name: "role", err: fmt.Errorf(`ent: validator failed for field "EnsembleProposer.role": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Model(); !ok {
		return &ValidationError{Name: "model", err: errors.New(`ent: missing required field "EnsembleProposer.model"`)}
	}
	if v, ok := _c.mutation.Model(); ok {
		if err := ensembleproposer.ModelValidator(v); err != nil {
			return &ValidationError{Name: "model", err: fmt.Errorf(`ent: validator failed for field "EnsembleProposer.model": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Platform(); !ok {
		return &ValidationError{Name: "platform", err: errors.New(`ent: missing required field "EnsembleProposer.platform"`)}
	}
	if v, ok := _c.mutation.Platform(); ok {
		if err := ensembleproposer.PlatformValidator(v); err != nil {
			return &ValidationError{Name: "platform", err: fmt.Errorf(`ent: validator failed for field "EnsembleProposer.platform": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Priority(); !ok {
		return &ValidationError{Name: "priority", err: errors.New(`ent: missing required field "EnsembleProposer.priority"`)}
	}
	if _, ok := _c.mutation.Enabled(); !ok {
		return &ValidationError{Name: "enabled", err: errors.New(`ent: missing required field "EnsembleProposer.enabled"`)}
	}
	if len(_c.mutation.GroupIDs()) == 0 {
		return &ValidationError{Name: "group", err: errors.New(`ent: missing required edge "EnsembleProposer.group"`)}
	}
	return nil
}

func (_c *EnsembleProposerCreate) sqlSave(ctx context.Context) (*EnsembleProposer, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *EnsembleProposerCreate) createSpec() (*EnsembleProposer, *sqlgraph.CreateSpec) {
	var (
		_node = &EnsembleProposer{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(ensembleproposer.Table, sqlgraph.NewFieldSpec(ensembleproposer.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(ensembleproposer.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(ensembleproposer.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.DeletedAt(); ok {
		_spec.SetField(ensembleproposer.FieldDeletedAt, field.TypeTime, value)
		_node.DeletedAt = &value
	}
	if value, ok := _c.mutation.Role(); ok {
		_spec.SetField(ensembleproposer.FieldRole, field.TypeString, value)
		_node.Role = value
	}
	if value, ok := _c.mutation.Model(); ok {
		_spec.SetField(ensembleproposer.FieldModel, field.TypeString, value)
		_node.Model = value
	}
	if value, ok := _c.mutation.Platform(); ok {
		_spec.SetField(ensembleproposer.FieldPlatform, field.TypeString, value)
		_node.Platform = value
	}
	if value, ok := _c.mutation.Priority(); ok {
		_spec.SetField(ensembleproposer.FieldPriority, field.TypeInt, value)
		_node.Priority = value
	}
	if value, ok := _c.mutation.Enabled(); ok {
		_spec.SetField(ensembleproposer.FieldEnabled, field.TypeBool, value)
		_node.Enabled = value
	}
	if nodes := _c.mutation.GroupIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   ensembleproposer.GroupTable,
			Columns: []string{ensembleproposer.GroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.GroupID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.EnsembleProposer.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.EnsembleProposerUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *EnsembleProposerCreate) OnConflict(opts ...sql.ConflictOption) *EnsembleProposerUpsertOne {
	_c.conflict = opts
	return &EnsembleProposerUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.EnsembleProposer.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *EnsembleProposerCreate) OnConflictColumns(columns ...string) *EnsembleProposerUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &EnsembleProposerUpsertOne{
		create: _c,
	}
}

type (
	// EnsembleProposerUpsertOne is the builder for "upsert"-ing
	//  one EnsembleProposer node.
	EnsembleProposerUpsertOne struct {
		create *EnsembleProposerCreate
	}

	// EnsembleProposerUpsert is the "OnConflict" setter.
	EnsembleProposerUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *EnsembleProposerUpsert) SetUpdatedAt(v time.Time) *EnsembleProposerUpsert {
	u.Set(ensembleproposer.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *EnsembleProposerUpsert) UpdateUpdatedAt() *EnsembleProposerUpsert {
	u.SetExcluded(ensembleproposer.FieldUpdatedAt)
	return u
}

// SetDeletedAt sets the "deleted_at" field.
func (u *EnsembleProposerUpsert) SetDeletedAt(v time.Time) *EnsembleProposerUpsert {
	u.Set(ensembleproposer.FieldDeletedAt, v)
	return u
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *EnsembleProposerUpsert) UpdateDeletedAt() *EnsembleProposerUpsert {
	u.SetExcluded(ensembleproposer.FieldDeletedAt)
	return u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *EnsembleProposerUpsert) ClearDeletedAt() *EnsembleProposerUpsert {
	u.SetNull(ensembleproposer.FieldDeletedAt)
	return u
}

// SetGroupID sets the "group_id" field.
func (u *EnsembleProposerUpsert) SetGroupID(v int64) *EnsembleProposerUpsert {
	u.Set(ensembleproposer.FieldGroupID, v)
	return u
}

// UpdateGroupID sets the "group_id" field to the value that was provided on create.
func (u *EnsembleProposerUpsert) UpdateGroupID() *EnsembleProposerUpsert {
	u.SetExcluded(ensembleproposer.FieldGroupID)
	return u
}

// SetRole sets the "role" field.
func (u *EnsembleProposerUpsert) SetRole(v string) *EnsembleProposerUpsert {
	u.Set(ensembleproposer.FieldRole, v)
	return u
}

// UpdateRole sets the "role" field to the value that was provided on create.
func (u *EnsembleProposerUpsert) UpdateRole() *EnsembleProposerUpsert {
	u.SetExcluded(ensembleproposer.FieldRole)
	return u
}

// SetModel sets the "model" field.
func (u *EnsembleProposerUpsert) SetModel(v string) *EnsembleProposerUpsert {
	u.Set(ensembleproposer.FieldModel, v)
	return u
}

// UpdateModel sets the "model" field to the value that was provided on create.
func (u *EnsembleProposerUpsert) UpdateModel() *EnsembleProposerUpsert {
	u.SetExcluded(ensembleproposer.FieldModel)
	return u
}

// SetPlatform sets the "platform" field.
func (u *EnsembleProposerUpsert) SetPlatform(v string) *EnsembleProposerUpsert {
	u.Set(ensembleproposer.FieldPlatform, v)
	return u
}

// UpdatePlatform sets the "platform" field to the value that was provided on create.
func (u *EnsembleProposerUpsert) UpdatePlatform() *EnsembleProposerUpsert {
	u.SetExcluded(ensembleproposer.FieldPlatform)
	return u
}

// SetPriority sets the "priority" field.
func (u *EnsembleProposerUpsert) SetPriority(v int) *EnsembleProposerUpsert {
	u.Set(ensembleproposer.FieldPriority, v)
	return u
}

// UpdatePriority sets the "priority" field to the value that was provided on create.
func (u *EnsembleProposerUpsert) UpdatePriority() *EnsembleProposerUpsert {
	u.SetExcluded(ensembleproposer.FieldPriority)
	return u
}

// AddPriority adds v to the "priority" field.
func (u *EnsembleProposerUpsert) AddPriority(v int) *EnsembleProposerUpsert {
	u.Add(ensembleproposer.FieldPriority, v)
	return u
}

// SetEnabled sets the "enabled" field.
func (u *EnsembleProposerUpsert) SetEnabled(v bool) *EnsembleProposerUpsert {
	u.Set(ensembleproposer.FieldEnabled, v)
	return u
}

// UpdateEnabled sets the "enabled" field to the value that was provided on create.
func (u *EnsembleProposerUpsert) UpdateEnabled() *EnsembleProposerUpsert {
	u.SetExcluded(ensembleproposer.FieldEnabled)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.EnsembleProposer.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *EnsembleProposerUpsertOne) UpdateNewValues() *EnsembleProposerUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(ensembleproposer.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.EnsembleProposer.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *EnsembleProposerUpsertOne) Ignore() *EnsembleProposerUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *EnsembleProposerUpsertOne) DoNothing() *EnsembleProposerUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the EnsembleProposerCreate.OnConflict
// documentation for more info.
func (u *EnsembleProposerUpsertOne) Update(set func(*EnsembleProposerUpsert)) *EnsembleProposerUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&EnsembleProposerUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *EnsembleProposerUpsertOne) SetUpdatedAt(v time.Time) *EnsembleProposerUpsertOne {
	return u.Update(func(s *EnsembleProposerUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *EnsembleProposerUpsertOne) UpdateUpdatedAt() *EnsembleProposerUpsertOne {
	return u.Update(func(s *EnsembleProposerUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetDeletedAt sets the "deleted_at" field.
func (u *EnsembleProposerUpsertOne) SetDeletedAt(v time.Time) *EnsembleProposerUpsertOne {
	return u.Update(func(s *EnsembleProposerUpsert) {
		s.SetDeletedAt(v)
	})
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *EnsembleProposerUpsertOne) UpdateDeletedAt() *EnsembleProposerUpsertOne {
	return u.Update(func(s *EnsembleProposerUpsert) {
		s.UpdateDeletedAt()
	})
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *EnsembleProposerUpsertOne) ClearDeletedAt() *EnsembleProposerUpsertOne {
	return u.Update(func(s *EnsembleProposerUpsert) {
		s.ClearDeletedAt()
	})
}

// SetGroupID sets the "group_id" field.
func (u *EnsembleProposerUpsertOne) SetGroupID(v int64) *EnsembleProposerUpsertOne {
	return u.Update(func(s *EnsembleProposerUpsert) {
		s.SetGroupID(v)
	})
}

// UpdateGroupID sets the "group_id" field to the value that was provided on create.
func (u *EnsembleProposerUpsertOne) UpdateGroupID() *EnsembleProposerUpsertOne {
	return u.Update(func(s *EnsembleProposerUpsert) {
		s.UpdateGroupID()
	})
}

// SetRole sets the "role" field.
func (u *EnsembleProposerUpsertOne) SetRole(v string) *EnsembleProposerUpsertOne {
	return u.Update(func(s *EnsembleProposerUpsert) {
		s.SetRole(v)
	})
}

// UpdateRole sets the "role" field to the value that was provided on create.
func (u *EnsembleProposerUpsertOne) UpdateRole() *EnsembleProposerUpsertOne {
	return u.Update(func(s *EnsembleProposerUpsert) {
		s.UpdateRole()
	})
}

// SetModel sets the "model" field.
func (u *EnsembleProposerUpsertOne) SetModel(v string) *EnsembleProposerUpsertOne {
	return u.Update(func(s *EnsembleProposerUpsert) {
		s.SetModel(v)
	})
}

// UpdateModel sets the "model" field to the value that was provided on create.
func (u *EnsembleProposerUpsertOne) UpdateModel() *EnsembleProposerUpsertOne {
	return u.Update(func(s *EnsembleProposerUpsert) {
		s.UpdateModel()
	})
}

// SetPlatform sets the "platform" field.
func (u *EnsembleProposerUpsertOne) SetPlatform(v string) *EnsembleProposerUpsertOne {
	return u.Update(func(s *EnsembleProposerUpsert) {
		s.SetPlatform(v)
	})
}

// UpdatePlatform sets the "platform" field to the value that was provided on create.
func (u *EnsembleProposerUpsertOne) UpdatePlatform() *EnsembleProposerUpsertOne {
	return u.Update(func(s *EnsembleProposerUpsert) {
		s.UpdatePlatform()
	})
}

// SetPriority sets the "priority" field.
func (u *EnsembleProposerUpsertOne) SetPriority(v int) *EnsembleProposerUpsertOne {
	return u.Update(func(s *EnsembleProposerUpsert) {
		s.SetPriority(v)
	})
}

// AddPriority adds v to the "priority" field.
func (u *EnsembleProposerUpsertOne) AddPriority(v int) *EnsembleProposerUpsertOne {
	return u.Update(func(s *EnsembleProposerUpsert) {
		s.AddPriority(v)
	})
}

// UpdatePriority sets the "priority" field to the value that was provided on create.
func (u *EnsembleProposerUpsertOne) UpdatePriority() *EnsembleProposerUpsertOne {
	return u.Update(func(s *EnsembleProposerUpsert) {
		s.UpdatePriority()
	})
}

// SetEnabled sets the "enabled" field.
func (u *EnsembleProposerUpsertOne) SetEnabled(v bool) *EnsembleProposerUpsertOne {
	return u.Update(func(s *EnsembleProposerUpsert) {
		s.SetEnabled(v)
	})
}

// UpdateEnabled sets the "enabled" field to the value that was provided on create.
func (u *EnsembleProposerUpsertOne) UpdateEnabled() *EnsembleProposerUpsertOne {
	return u.Update(func(s *EnsembleProposerUpsert) {
		s.UpdateEnabled()
	})
}

// Exec executes the query.
func (u *EnsembleProposerUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for EnsembleProposerCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *EnsembleProposerUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *EnsembleProposerUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *EnsembleProposerUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// EnsembleProposerCreateBulk is the builder for creating many EnsembleProposer entities in bulk.
type EnsembleProposerCreateBulk struct {
	config
	err      error
	builders []*EnsembleProposerCreate
	conflict []sql.ConflictOption
}

// Save creates the EnsembleProposer entities in the database.
func (_c *EnsembleProposerCreateBulk) Save(ctx context.Context) ([]*EnsembleProposer, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*EnsembleProposer, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*EnsembleProposerMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *EnsembleProposerCreateBulk) SaveX(ctx context.Context) []*EnsembleProposer {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *EnsembleProposerCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *EnsembleProposerCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.EnsembleProposer.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.EnsembleProposerUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *EnsembleProposerCreateBulk) OnConflict(opts ...sql.ConflictOption) *EnsembleProposerUpsertBulk {
	_c.conflict = opts
	return &EnsembleProposerUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.EnsembleProposer.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *EnsembleProposerCreateBulk) OnConflictColumns(columns ...string) *EnsembleProposerUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &EnsembleProposerUpsertBulk{
		create: _c,
	}
}

// EnsembleProposerUpsertBulk is the builder for "upsert"-ing
// a bulk of EnsembleProposer nodes.
type EnsembleProposerUpsertBulk struct {
	create *EnsembleProposerCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.EnsembleProposer.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *EnsembleProposerUpsertBulk) UpdateNewValues() *EnsembleProposerUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(ensembleproposer.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.EnsembleProposer.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *EnsembleProposerUpsertBulk) Ignore() *EnsembleProposerUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *EnsembleProposerUpsertBulk) DoNothing() *EnsembleProposerUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the EnsembleProposerCreateBulk.OnConflict
// documentation for more info.
func (u *EnsembleProposerUpsertBulk) Update(set func(*EnsembleProposerUpsert)) *EnsembleProposerUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&EnsembleProposerUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *EnsembleProposerUpsertBulk) SetUpdatedAt(v time.Time) *EnsembleProposerUpsertBulk {
	return u.Update(func(s *EnsembleProposerUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *EnsembleProposerUpsertBulk) UpdateUpdatedAt() *EnsembleProposerUpsertBulk {
	return u.Update(func(s *EnsembleProposerUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetDeletedAt sets the "deleted_at" field.
func (u *EnsembleProposerUpsertBulk) SetDeletedAt(v time.Time) *EnsembleProposerUpsertBulk {
	return u.Update(func(s *EnsembleProposerUpsert) {
		s.SetDeletedAt(v)
	})
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *EnsembleProposerUpsertBulk) UpdateDeletedAt() *EnsembleProposerUpsertBulk {
	return u.Update(func(s *EnsembleProposerUpsert) {
		s.UpdateDeletedAt()
	})
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *EnsembleProposerUpsertBulk) ClearDeletedAt() *EnsembleProposerUpsertBulk {
	return u.Update(func(s *EnsembleProposerUpsert) {
		s.ClearDeletedAt()
	})
}

// SetGroupID sets the "group_id" field.
func (u *EnsembleProposerUpsertBulk) SetGroupID(v int64) *EnsembleProposerUpsertBulk {
	return u.Update(func(s *EnsembleProposerUpsert) {
		s.SetGroupID(v)
	})
}

// UpdateGroupID sets the "group_id" field to the value that was provided on create.
func (u *EnsembleProposerUpsertBulk) UpdateGroupID() *EnsembleProposerUpsertBulk {
	return u.Update(func(s *EnsembleProposerUpsert) {
		s.UpdateGroupID()
	})
}

// SetRole sets the "role" field.
func (u *EnsembleProposerUpsertBulk) SetRole(v string) *EnsembleProposerUpsertBulk {
	return u.Update(func(s *EnsembleProposerUpsert) {
		s.SetRole(v)
	})
}

// UpdateRole sets the "role" field to the value that was provided on create.
func (u *EnsembleProposerUpsertBulk) UpdateRole() *EnsembleProposerUpsertBulk {
	return u.Update(func(s *EnsembleProposerUpsert) {
		s.UpdateRole()
	})
}

// SetModel sets the "model" field.
func (u *EnsembleProposerUpsertBulk) SetModel(v string) *EnsembleProposerUpsertBulk {
	return u.Update(func(s *EnsembleProposerUpsert) {
		s.SetModel(v)
	})
}

// UpdateModel sets the "model" field to the value that was provided on create.
func (u *EnsembleProposerUpsertBulk) UpdateModel() *EnsembleProposerUpsertBulk {
	return u.Update(func(s *EnsembleProposerUpsert) {
		s.UpdateModel()
	})
}

// SetPlatform sets the "platform" field.
func (u *EnsembleProposerUpsertBulk) SetPlatform(v string) *EnsembleProposerUpsertBulk {
	return u.Update(func(s *EnsembleProposerUpsert) {
		s.SetPlatform(v)
	})
}

// UpdatePlatform sets the "platform" field to the value that was provided on create.
func (u *EnsembleProposerUpsertBulk) UpdatePlatform() *EnsembleProposerUpsertBulk {
	return u.Update(func(s *EnsembleProposerUpsert) {
		s.UpdatePlatform()
	})
}

// SetPriority sets the "priority" field.
func (u *EnsembleProposerUpsertBulk) SetPriority(v int) *EnsembleProposerUpsertBulk {
	return u.Update(func(s *EnsembleProposerUpsert) {
		s.SetPriority(v)
	})
}

// AddPriority adds v to the "priority" field.
func (u *EnsembleProposerUpsertBulk) AddPriority(v int) *EnsembleProposerUpsertBulk {
	return u.Update(func(s *EnsembleProposerUpsert) {
		s.AddPriority(v)
	})
}

// UpdatePriority sets the "priority" field to the value that was provided on create.
func (u *EnsembleProposerUpsertBulk) UpdatePriority() *EnsembleProposerUpsertBulk {
	return u.Update(func(s *EnsembleProposerUpsert) {
		s.UpdatePriority()
	})
}

// SetEnabled sets the "enabled" field.
func (u *EnsembleProposerUpsertBulk) SetEnabled(v bool) *EnsembleProposerUpsertBulk {
	return u.Update(func(s *EnsembleProposerUpsert) {
		s.SetEnabled(v)
	})
}

// UpdateEnabled sets the "enabled" field to the value that was provided on create.
func (u *EnsembleProposerUpsertBulk) UpdateEnabled() *EnsembleProposerUpsertBulk {
	return u.Update(func(s *EnsembleProposerUpsert) {
		s.UpdateEnabled()
	})
}

// Exec executes the query.
func (u *EnsembleProposerUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the EnsembleProposerCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for EnsembleProposerCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *EnsembleProposerUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
